name: Dependency Submission

on:
  push:
  workflow_dispatch:

jobs:
  maintenance_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.1
      - uses: actions/setup-java@v4.4.0
        name: Setup Java
        with:
          distribution: temurin
          java-version: 17
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.1.0
        env:
          CODEARTIFACT_AUTH_TOKEN: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          # Include only relevant configurations
          dependency-graph-include-configurations: '(implementation|api|compileClasspath|runtimeClasspath)'
